services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: dora_metrics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana:latest
    # Elimina network_mode si existe
    ports:
      - "3000:3000"  # Esto mapea el puerto 3000 del contenedor al puerto 3000 del host
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  postgres_data:
  grafana_data: